name: interpretability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy<2
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
      - transformer-lens
      - tqdm
      - plotly
      - ipykernel
      - seaborn
